# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MappingForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MappingForm(object):
    def setupUi(self, MappingForm):
        MappingForm.setObjectName("MappingForm")
        MappingForm.resize(1128, 766)
        self.gridLayoutWidget = QtWidgets.QWidget(MappingForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 50, 507, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.fctIDRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctIDRepLdt.setClearButtonEnabled(False)
        self.fctIDRepLdt.setObjectName("fctIDRepLdt")
        self.gridLayout.addWidget(self.fctIDRepLdt, 1, 2, 1, 1)
        self.fctCriticalityRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctCriticalityRepLdt.setObjectName("fctCriticalityRepLdt")
        self.gridLayout.addWidget(self.fctCriticalityRepLdt, 5, 2, 1, 1)
        self.fctUsageRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctUsageRepLdt.setObjectName("fctUsageRepLdt")
        self.gridLayout.addWidget(self.fctUsageRepLdt, 6, 2, 1, 1)
        self.fctCriticalitySpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.fctCriticalitySpin.setMinimum(0)
        self.fctCriticalitySpin.setProperty("value", 0)
        self.fctCriticalitySpin.setObjectName("fctCriticalitySpin")
        self.gridLayout.addWidget(self.fctCriticalitySpin, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.fctDescriptionSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.fctDescriptionSpin.setMinimum(0)
        self.fctDescriptionSpin.setProperty("value", 0)
        self.fctDescriptionSpin.setObjectName("fctDescriptionSpin")
        self.gridLayout.addWidget(self.fctDescriptionSpin, 4, 1, 1, 1)
        self.fctNameRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctNameRepLdt.setObjectName("fctNameRepLdt")
        self.gridLayout.addWidget(self.fctNameRepLdt, 2, 2, 1, 1)
        self.fctChannelSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.fctChannelSpin.setMinimum(0)
        self.fctChannelSpin.setProperty("value", 3)
        self.fctChannelSpin.setObjectName("fctChannelSpin")
        self.gridLayout.addWidget(self.fctChannelSpin, 3, 1, 1, 1)
        self.fctIDSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.fctIDSpin.setMinimum(0)
        self.fctIDSpin.setProperty("value", 0)
        self.fctIDSpin.setObjectName("fctIDSpin")
        self.gridLayout.addWidget(self.fctIDSpin, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.fctNameSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.fctNameSpin.setMinimum(0)
        self.fctNameSpin.setProperty("value", 0)
        self.fctNameSpin.setObjectName("fctNameSpin")
        self.gridLayout.addWidget(self.fctNameSpin, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.fctDescriptionRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctDescriptionRepLdt.setObjectName("fctDescriptionRepLdt")
        self.gridLayout.addWidget(self.fctDescriptionRepLdt, 4, 2, 1, 1)
        self.fctUsageSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.fctUsageSpin.setMinimum(0)
        self.fctUsageSpin.setProperty("value", 0)
        self.fctUsageSpin.setObjectName("fctUsageSpin")
        self.gridLayout.addWidget(self.fctUsageSpin, 6, 1, 1, 1)
        self.fctChannelRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctChannelRepLdt.setObjectName("fctChannelRepLdt")
        self.gridLayout.addWidget(self.fctChannelRepLdt, 3, 2, 1, 1)
        self.fctIDHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctIDHeaderLdt.setObjectName("fctIDHeaderLdt")
        self.gridLayout.addWidget(self.fctIDHeaderLdt, 1, 3, 1, 1)
        self.fctNameHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctNameHeaderLdt.setObjectName("fctNameHeaderLdt")
        self.gridLayout.addWidget(self.fctNameHeaderLdt, 2, 3, 1, 1)
        self.fctChannelHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctChannelHeaderLdt.setObjectName("fctChannelHeaderLdt")
        self.gridLayout.addWidget(self.fctChannelHeaderLdt, 3, 3, 1, 1)
        self.fctDescriptionHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctDescriptionHeaderLdt.setObjectName("fctDescriptionHeaderLdt")
        self.gridLayout.addWidget(self.fctDescriptionHeaderLdt, 4, 3, 1, 1)
        self.fctCriticalityHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctCriticalityHeaderLdt.setObjectName("fctCriticalityHeaderLdt")
        self.gridLayout.addWidget(self.fctCriticalityHeaderLdt, 5, 3, 1, 1)
        self.fctUsageHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fctUsageHeaderLdt.setObjectName("fctUsageHeaderLdt")
        self.gridLayout.addWidget(self.fctUsageHeaderLdt, 6, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(MappingForm)
        self.label_10.setGeometry(QtCore.QRect(36, 20, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(MappingForm)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(560, 50, 496, 462))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 8, 0, 1, 1)
        self.ucIDSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucIDSpin.setMinimum(0)
        self.ucIDSpin.setProperty("value", 0)
        self.ucIDSpin.setObjectName("ucIDSpin")
        self.gridLayout_2.addWidget(self.ucIDSpin, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 9, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 10, 0, 1, 1)
        self.ucAutomatedRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucAutomatedRepLdt.setObjectName("ucAutomatedRepLdt")
        self.gridLayout_2.addWidget(self.ucAutomatedRepLdt, 12, 2, 1, 1)
        self.ucAutomatableRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucAutomatableRepLdt.setObjectName("ucAutomatableRepLdt")
        self.gridLayout_2.addWidget(self.ucAutomatableRepLdt, 13, 2, 1, 1)
        self.ucReleaseRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucReleaseRepLdt.setObjectName("ucReleaseRepLdt")
        self.gridLayout_2.addWidget(self.ucReleaseRepLdt, 14, 2, 1, 1)
        self.ucFunctionalityRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucFunctionalityRepLdt.setObjectName("ucFunctionalityRepLdt")
        self.gridLayout_2.addWidget(self.ucFunctionalityRepLdt, 15, 2, 1, 1)
        self.ucAutomatonRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucAutomatonRepLdt.setObjectName("ucAutomatonRepLdt")
        self.gridLayout_2.addWidget(self.ucAutomatonRepLdt, 16, 2, 1, 1)
        self.ucAverageSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucAverageSpin.setMinimum(0)
        self.ucAverageSpin.setProperty("value", 0)
        self.ucAverageSpin.setObjectName("ucAverageSpin")
        self.gridLayout_2.addWidget(self.ucAverageSpin, 11, 1, 1, 1)
        self.ucCriticalSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucCriticalSpin.setMinimum(0)
        self.ucCriticalSpin.setProperty("value", 0)
        self.ucCriticalSpin.setObjectName("ucCriticalSpin")
        self.gridLayout_2.addWidget(self.ucCriticalSpin, 10, 1, 1, 1)
        self.ucAutomatedSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucAutomatedSpin.setMinimum(0)
        self.ucAutomatedSpin.setProperty("value", 0)
        self.ucAutomatedSpin.setObjectName("ucAutomatedSpin")
        self.gridLayout_2.addWidget(self.ucAutomatedSpin, 12, 1, 1, 1)
        self.ucAutomatableSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucAutomatableSpin.setMinimum(0)
        self.ucAutomatableSpin.setProperty("value", 0)
        self.ucAutomatableSpin.setObjectName("ucAutomatableSpin")
        self.gridLayout_2.addWidget(self.ucAutomatableSpin, 13, 1, 1, 1)
        self.ucReleaseSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucReleaseSpin.setMinimum(0)
        self.ucReleaseSpin.setProperty("value", 0)
        self.ucReleaseSpin.setObjectName("ucReleaseSpin")
        self.gridLayout_2.addWidget(self.ucReleaseSpin, 14, 1, 1, 1)
        self.ucAutomatonSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucAutomatonSpin.setMinimum(0)
        self.ucAutomatonSpin.setProperty("value", 0)
        self.ucAutomatonSpin.setObjectName("ucAutomatonSpin")
        self.gridLayout_2.addWidget(self.ucAutomatonSpin, 16, 1, 1, 1)
        self.ucIDRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucIDRepLdt.setObjectName("ucIDRepLdt")
        self.gridLayout_2.addWidget(self.ucIDRepLdt, 1, 2, 1, 1)
        self.ucNameRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucNameRepLdt.setObjectName("ucNameRepLdt")
        self.gridLayout_2.addWidget(self.ucNameRepLdt, 2, 2, 1, 1)
        self.ucDescriptionRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucDescriptionRepLdt.setObjectName("ucDescriptionRepLdt")
        self.gridLayout_2.addWidget(self.ucDescriptionRepLdt, 3, 2, 1, 1)
        self.ucPreRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucPreRepLdt.setObjectName("ucPreRepLdt")
        self.gridLayout_2.addWidget(self.ucPreRepLdt, 4, 2, 1, 1)
        self.ucStepsRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucStepsRepLdt.setObjectName("ucStepsRepLdt")
        self.gridLayout_2.addWidget(self.ucStepsRepLdt, 5, 2, 1, 1)
        self.ucPostRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucPostRepLdt.setObjectName("ucPostRepLdt")
        self.gridLayout_2.addWidget(self.ucPostRepLdt, 6, 2, 1, 1)
        self.ucExcpRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucExcpRepLdt.setObjectName("ucExcpRepLdt")
        self.gridLayout_2.addWidget(self.ucExcpRepLdt, 7, 2, 1, 1)
        self.ucRequireRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucRequireRepLdt.setObjectName("ucRequireRepLdt")
        self.gridLayout_2.addWidget(self.ucRequireRepLdt, 8, 2, 1, 1)
        self.ucAverageRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucAverageRepLdt.setObjectName("ucAverageRepLdt")
        self.gridLayout_2.addWidget(self.ucAverageRepLdt, 11, 2, 1, 1)
        self.ucTypeRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucTypeRepLdt.setObjectName("ucTypeRepLdt")
        self.gridLayout_2.addWidget(self.ucTypeRepLdt, 9, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 11, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 12, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 13, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 14, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 15, 0, 1, 1)
        self.ucNameSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucNameSpin.setMinimum(0)
        self.ucNameSpin.setProperty("value", 7)
        self.ucNameSpin.setObjectName("ucNameSpin")
        self.gridLayout_2.addWidget(self.ucNameSpin, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 16, 0, 1, 1)
        self.ucCriticalRepLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucCriticalRepLdt.setObjectName("ucCriticalRepLdt")
        self.gridLayout_2.addWidget(self.ucCriticalRepLdt, 10, 2, 1, 1)
        self.ucDescriptionSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucDescriptionSpin.setMinimum(0)
        self.ucDescriptionSpin.setProperty("value", 0)
        self.ucDescriptionSpin.setObjectName("ucDescriptionSpin")
        self.gridLayout_2.addWidget(self.ucDescriptionSpin, 3, 1, 1, 1)
        self.ucPreSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucPreSpin.setMinimum(0)
        self.ucPreSpin.setProperty("value", 10)
        self.ucPreSpin.setObjectName("ucPreSpin")
        self.gridLayout_2.addWidget(self.ucPreSpin, 4, 1, 1, 1)
        self.ucStepsSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucStepsSpin.setMinimum(0)
        self.ucStepsSpin.setProperty("value", 7)
        self.ucStepsSpin.setObjectName("ucStepsSpin")
        self.gridLayout_2.addWidget(self.ucStepsSpin, 5, 1, 1, 1)
        self.ucPostSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucPostSpin.setMinimum(0)
        self.ucPostSpin.setProperty("value", 8)
        self.ucPostSpin.setObjectName("ucPostSpin")
        self.gridLayout_2.addWidget(self.ucPostSpin, 6, 1, 1, 1)
        self.ucExcpSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucExcpSpin.setMinimum(0)
        self.ucExcpSpin.setProperty("value", 0)
        self.ucExcpSpin.setObjectName("ucExcpSpin")
        self.gridLayout_2.addWidget(self.ucExcpSpin, 7, 1, 1, 1)
        self.ucRequireSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucRequireSpin.setMinimum(0)
        self.ucRequireSpin.setProperty("value", 0)
        self.ucRequireSpin.setObjectName("ucRequireSpin")
        self.gridLayout_2.addWidget(self.ucRequireSpin, 8, 1, 1, 1)
        self.ucTypeSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucTypeSpin.setMinimum(0)
        self.ucTypeSpin.setProperty("value", 0)
        self.ucTypeSpin.setObjectName("ucTypeSpin")
        self.gridLayout_2.addWidget(self.ucTypeSpin, 9, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 5, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 7, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 0, 3, 1, 1)
        self.ucIDHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucIDHeaderLdt.setObjectName("ucIDHeaderLdt")
        self.gridLayout_2.addWidget(self.ucIDHeaderLdt, 1, 3, 1, 1)
        self.ucNameHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucNameHeaderLdt.setObjectName("ucNameHeaderLdt")
        self.gridLayout_2.addWidget(self.ucNameHeaderLdt, 2, 3, 1, 1)
        self.ucDescriptionHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucDescriptionHeaderLdt.setObjectName("ucDescriptionHeaderLdt")
        self.gridLayout_2.addWidget(self.ucDescriptionHeaderLdt, 3, 3, 1, 1)
        self.ucPreHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucPreHeaderLdt.setObjectName("ucPreHeaderLdt")
        self.gridLayout_2.addWidget(self.ucPreHeaderLdt, 4, 3, 1, 1)
        self.ucStepsHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucStepsHeaderLdt.setObjectName("ucStepsHeaderLdt")
        self.gridLayout_2.addWidget(self.ucStepsHeaderLdt, 5, 3, 1, 1)
        self.ucPostHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucPostHeaderLdt.setObjectName("ucPostHeaderLdt")
        self.gridLayout_2.addWidget(self.ucPostHeaderLdt, 6, 3, 1, 1)
        self.ucExcpHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucExcpHeaderLdt.setObjectName("ucExcpHeaderLdt")
        self.gridLayout_2.addWidget(self.ucExcpHeaderLdt, 7, 3, 1, 1)
        self.ucRequireHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucRequireHeaderLdt.setObjectName("ucRequireHeaderLdt")
        self.gridLayout_2.addWidget(self.ucRequireHeaderLdt, 8, 3, 1, 1)
        self.ucCriticalHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucCriticalHeaderLdt.setObjectName("ucCriticalHeaderLdt")
        self.gridLayout_2.addWidget(self.ucCriticalHeaderLdt, 10, 3, 1, 1)
        self.ucTypeHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucTypeHeaderLdt.setObjectName("ucTypeHeaderLdt")
        self.gridLayout_2.addWidget(self.ucTypeHeaderLdt, 9, 3, 1, 1)
        self.ucAverageHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucAverageHeaderLdt.setObjectName("ucAverageHeaderLdt")
        self.gridLayout_2.addWidget(self.ucAverageHeaderLdt, 11, 3, 1, 1)
        self.ucAutomatedHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucAutomatedHeaderLdt.setObjectName("ucAutomatedHeaderLdt")
        self.gridLayout_2.addWidget(self.ucAutomatedHeaderLdt, 12, 3, 1, 1)
        self.ucAutomatableHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucAutomatableHeaderLdt.setObjectName("ucAutomatableHeaderLdt")
        self.gridLayout_2.addWidget(self.ucAutomatableHeaderLdt, 13, 3, 1, 1)
        self.ucReleaseHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucReleaseHeaderLdt.setObjectName("ucReleaseHeaderLdt")
        self.gridLayout_2.addWidget(self.ucReleaseHeaderLdt, 14, 3, 1, 1)
        self.ucFunctionalityHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucFunctionalityHeaderLdt.setObjectName("ucFunctionalityHeaderLdt")
        self.gridLayout_2.addWidget(self.ucFunctionalityHeaderLdt, 15, 3, 1, 1)
        self.ucAutomatonHeaderLdt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.ucAutomatonHeaderLdt.setObjectName("ucAutomatonHeaderLdt")
        self.gridLayout_2.addWidget(self.ucAutomatonHeaderLdt, 16, 3, 1, 1)
        self.ucFunctionalitySpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ucFunctionalitySpin.setMinimum(0)
        self.ucFunctionalitySpin.setProperty("value", 0)
        self.ucFunctionalitySpin.setObjectName("ucFunctionalitySpin")
        self.gridLayout_2.addWidget(self.ucFunctionalitySpin, 15, 1, 1, 1)
        self.okBtn = QtWidgets.QPushButton(MappingForm)
        self.okBtn.setGeometry(QtCore.QRect(820, 630, 75, 23))
        self.okBtn.setObjectName("okBtn")
        self.cancelBtn = QtWidgets.QPushButton(MappingForm)
        self.cancelBtn.setGeometry(QtCore.QRect(910, 630, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.label_14 = QtWidgets.QLabel(MappingForm)
        self.label_14.setGeometry(QtCore.QRect(570, 20, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_31 = QtWidgets.QLabel(MappingForm)
        self.label_31.setGeometry(QtCore.QRect(40, 290, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(MappingForm)
        self.label_32.setGeometry(QtCore.QRect(40, 320, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.headerRowSpin = QtWidgets.QSpinBox(MappingForm)
        self.headerRowSpin.setGeometry(QtCore.QRect(140, 290, 42, 22))
        self.headerRowSpin.setObjectName("headerRowSpin")
        self.firstDataRowSpin = QtWidgets.QSpinBox(MappingForm)
        self.firstDataRowSpin.setGeometry(QtCore.QRect(140, 320, 42, 22))
        self.firstDataRowSpin.setObjectName("firstDataRowSpin")
        self.label_35 = QtWidgets.QLabel(MappingForm)
        self.label_35.setGeometry(QtCore.QRect(40, 360, 491, 391))
        self.label_35.setObjectName("label_35")

        self.retranslateUi(MappingForm)
        QtCore.QMetaObject.connectSlotsByName(MappingForm)

    def retranslateUi(self, MappingForm):
        _translate = QtCore.QCoreApplication.translate
        MappingForm.setWindowTitle(_translate("MappingForm", "Dialog"))
        self.label_5.setText(_translate("MappingForm", "Functionality Channel"))
        self.label_4.setText(_translate("MappingForm", "Replacement text"))
        self.label_3.setText(_translate("MappingForm", "Import column"))
        self.label_2.setText(_translate("MappingForm", "Mapped field"))
        self.label.setText(_translate("MappingForm", "Functionality Name"))
        self.label_6.setText(_translate("MappingForm", "Functionality Description"))
        self.label_7.setText(_translate("MappingForm", "Functionality ID"))
        self.label_9.setText(_translate("MappingForm", "Functionality Usage"))
        self.label_8.setText(_translate("MappingForm", "Functionality Criticality"))
        self.label_33.setText(_translate("MappingForm", "Header text"))
        self.label_10.setText(_translate("MappingForm", "Functionality Mapping"))
        self.label_22.setText(_translate("MappingForm", "Require Usecase"))
        self.label_13.setText(_translate("MappingForm", "Replacement text"))
        self.label_23.setText(_translate("MappingForm", "Test Type"))
        self.label_20.setText(_translate("MappingForm", "Post Condition"))
        self.label_11.setText(_translate("MappingForm", "Mapped field"))
        self.label_24.setText(_translate("MappingForm", "Critical Path"))
        self.label_25.setText(_translate("MappingForm", "Average Run Time"))
        self.label_26.setText(_translate("MappingForm", "Automated"))
        self.label_27.setText(_translate("MappingForm", "Automatable"))
        self.label_28.setText(_translate("MappingForm", "Release"))
        self.label_29.setText(_translate("MappingForm", "Functionality link"))
        self.label_30.setText(_translate("MappingForm", "Automaton link"))
        self.label_15.setText(_translate("MappingForm", "ID"))
        self.label_12.setText(_translate("MappingForm", "Import column"))
        self.label_18.setText(_translate("MappingForm", "Pre Requisite"))
        self.label_19.setText(_translate("MappingForm", "Steps"))
        self.label_17.setText(_translate("MappingForm", "Short Description"))
        self.label_16.setText(_translate("MappingForm", "Name"))
        self.label_21.setText(_translate("MappingForm", "Exceptional Behaviour"))
        self.label_34.setText(_translate("MappingForm", "Header text"))
        self.okBtn.setText(_translate("MappingForm", "Ok"))
        self.cancelBtn.setText(_translate("MappingForm", "Cancel"))
        self.label_14.setText(_translate("MappingForm", "Use case Mapping"))
        self.label_31.setText(_translate("MappingForm", "Header row"))
        self.label_32.setText(_translate("MappingForm", "First data row"))
        self.label_35.setText(_translate("MappingForm", "<h1>Information</h1>\n"
"<h2>Purpose</h2>\n"
"This aim to map the excel spreadsheet column with the application data field.\n"
"<h2>General</h2>\n"
"<ul>\n"
"<li>Column start at 1</li>\n"
"<li>Replacement text : used </li>\n"
"</ul>"))

