# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FeatureForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeatureForm(object):
    def setupUi(self, FeatureForm):
        FeatureForm.setObjectName("FeatureForm")
        FeatureForm.resize(1356, 785)
        self.verticalLayout = QtWidgets.QVBoxLayout(FeatureForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.featureIWantLdt = QtWidgets.QLineEdit(FeatureForm)
        self.featureIWantLdt.setObjectName("featureIWantLdt")
        self.gridLayout.addWidget(self.featureIWantLdt, 2, 1, 1, 1)
        self.featureSoThatLdt = QtWidgets.QLineEdit(FeatureForm)
        self.featureSoThatLdt.setObjectName("featureSoThatLdt")
        self.gridLayout.addWidget(self.featureSoThatLdt, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(FeatureForm)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(FeatureForm)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.featureAsLdt = QtWidgets.QLineEdit(FeatureForm)
        self.featureAsLdt.setObjectName("featureAsLdt")
        self.gridLayout.addWidget(self.featureAsLdt, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(FeatureForm)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(FeatureForm)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.ID = QtWidgets.QLabel(FeatureForm)
        self.ID.setAlignment(QtCore.Qt.AlignCenter)
        self.ID.setObjectName("ID")
        self.gridLayout.addWidget(self.ID, 0, 0, 1, 1)
        self.featureNameLdt = QtWidgets.QLineEdit(FeatureForm)
        self.featureNameLdt.setObjectName("featureNameLdt")
        self.gridLayout.addWidget(self.featureNameLdt, 0, 1, 1, 1)
        self.improvementLbl = QtWidgets.QLabel(FeatureForm)
        self.improvementLbl.setTextFormat(QtCore.Qt.PlainText)
        self.improvementLbl.setObjectName("improvementLbl")
        self.gridLayout.addWidget(self.improvementLbl, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.epicCbx = QtWidgets.QComboBox(FeatureForm)
        self.epicCbx.setMinimumSize(QtCore.QSize(180, 0))
        self.epicCbx.setObjectName("epicCbx")
        self.horizontalLayout_4.addWidget(self.epicCbx)
        self.addEpicBtn = QtWidgets.QPushButton(FeatureForm)
        self.addEpicBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.addEpicBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.addEpicBtn.setObjectName("addEpicBtn")
        self.horizontalLayout_4.addWidget(self.addEpicBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(FeatureForm)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.businessValueLdt = QtWidgets.QLineEdit(FeatureForm)
        self.businessValueLdt.setObjectName("businessValueLdt")
        self.horizontalLayout_4.addWidget(self.businessValueLdt)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(FeatureForm)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.statusLdt = QtWidgets.QLineEdit(FeatureForm)
        self.statusLdt.setObjectName("statusLdt")
        self.horizontalLayout_4.addWidget(self.statusLdt)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 1, 1, 1)
        self.improvementTdt = QtWidgets.QTextEdit(FeatureForm)
        self.improvementTdt.setMinimumSize(QtCore.QSize(0, 30))
        self.improvementTdt.setMaximumSize(QtCore.QSize(16777215, 60))
        self.improvementTdt.setObjectName("improvementTdt")
        self.gridLayout.addWidget(self.improvementTdt, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(FeatureForm)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.featureSummaryTdt = QtWidgets.QTextEdit(FeatureForm)
        self.featureSummaryTdt.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.featureSummaryTdt.setObjectName("featureSummaryTdt")
        self.verticalLayout_3.addWidget(self.featureSummaryTdt)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.editBtn = QtWidgets.QPushButton(FeatureForm)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout_5.addWidget(self.editBtn)
        self.cancelEditBtn = QtWidgets.QPushButton(FeatureForm)
        self.cancelEditBtn.setObjectName("cancelEditBtn")
        self.horizontalLayout_5.addWidget(self.cancelEditBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_3, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addFeatureBtn = QtWidgets.QPushButton(FeatureForm)
        self.addFeatureBtn.setObjectName("addFeatureBtn")
        self.verticalLayout_2.addWidget(self.addFeatureBtn)
        self.resetBtn = QtWidgets.QPushButton(FeatureForm)
        self.resetBtn.setObjectName("resetBtn")
        self.verticalLayout_2.addWidget(self.resetBtn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.cancelBtn = QtWidgets.QPushButton(FeatureForm)
        self.cancelBtn.setObjectName("cancelBtn")
        self.verticalLayout_2.addWidget(self.cancelBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(FeatureForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.addScenarioBtn = QtWidgets.QPushButton(FeatureForm)
        self.addScenarioBtn.setObjectName("addScenarioBtn")
        self.horizontalLayout_2.addWidget(self.addScenarioBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.scenariosTab = QtWidgets.QTableWidget(FeatureForm)
        self.scenariosTab.setMinimumSize(QtCore.QSize(0, 90))
        self.scenariosTab.setMaximumSize(QtCore.QSize(16777215, 120))
        self.scenariosTab.setObjectName("scenariosTab")
        self.scenariosTab.setColumnCount(0)
        self.scenariosTab.setRowCount(0)
        self.verticalLayout.addWidget(self.scenariosTab)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(FeatureForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.addAttachmentBtn = QtWidgets.QPushButton(FeatureForm)
        self.addAttachmentBtn.setObjectName("addAttachmentBtn")
        self.horizontalLayout_3.addWidget(self.addAttachmentBtn)
        self.addGraphBtn = QtWidgets.QPushButton(FeatureForm)
        self.addGraphBtn.setObjectName("addGraphBtn")
        self.horizontalLayout_3.addWidget(self.addGraphBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.attachmentsTab = QtWidgets.QTableWidget(FeatureForm)
        self.attachmentsTab.setMinimumSize(QtCore.QSize(0, 90))
        self.attachmentsTab.setMaximumSize(QtCore.QSize(16777215, 120))
        self.attachmentsTab.setObjectName("attachmentsTab")
        self.attachmentsTab.setColumnCount(0)
        self.attachmentsTab.setRowCount(0)
        self.attachmentsTab.horizontalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.attachmentsTab)

        self.retranslateUi(FeatureForm)
        QtCore.QMetaObject.connectSlotsByName(FeatureForm)
        FeatureForm.setTabOrder(self.featureNameLdt, self.featureAsLdt)

    def retranslateUi(self, FeatureForm):
        _translate = QtCore.QCoreApplication.translate
        FeatureForm.setWindowTitle(_translate("FeatureForm", "Dialog"))
        self.label_6.setText(_translate("FeatureForm", "So that"))
        self.label.setText(_translate("FeatureForm", "I want"))
        self.label_2.setText(_translate("FeatureForm", "As"))
        self.label_3.setText(_translate("FeatureForm", "Summary"))
        self.ID.setText(_translate("FeatureForm", "Feature"))
        self.improvementLbl.setText(_translate("FeatureForm", "Improvement\n"
"Description"))
        self.addEpicBtn.setText(_translate("FeatureForm", "+"))
        self.label_8.setText(_translate("FeatureForm", "Business\n"
"Value"))
        self.label_9.setText(_translate("FeatureForm", "Status"))
        self.label_7.setText(_translate("FeatureForm", "Epic"))
        self.editBtn.setText(_translate("FeatureForm", "Edit"))
        self.cancelEditBtn.setText(_translate("FeatureForm", "Cancel"))
        self.addFeatureBtn.setText(_translate("FeatureForm", "Add"))
        self.resetBtn.setText(_translate("FeatureForm", "Reset"))
        self.cancelBtn.setText(_translate("FeatureForm", "Cancel"))
        self.label_4.setText(_translate("FeatureForm", "Scenarios"))
        self.addScenarioBtn.setText(_translate("FeatureForm", "Add scenario"))
        self.label_5.setText(_translate("FeatureForm", "Attachments"))
        self.addAttachmentBtn.setText(_translate("FeatureForm", "Add an attachment"))
        self.addGraphBtn.setText(_translate("FeatureForm", "Add a UML graph"))

