# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FeatureForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FunctionalityForm(object):
    def setupUi(self, FunctionalityForm):
        FunctionalityForm.setObjectName("FunctionalityForm")
        FunctionalityForm.resize(1356, 784)
        self.gridLayoutWidget = QtWidgets.QWidget(FunctionalityForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 1101, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.channelCmb = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.channelCmb.setEditable(False)
        self.channelCmb.setObjectName("channelCmb")
        self.gridLayout.addWidget(self.channelCmb, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.nameLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nameLdt.setObjectName("nameLdt")
        self.gridLayout.addWidget(self.nameLdt, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.ID = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ID.setObjectName("ID")
        self.gridLayout.addWidget(self.ID, 0, 0, 1, 1)
        self.idLdt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.idLdt.setObjectName("idLdt")
        self.gridLayout.addWidget(self.idLdt, 0, 1, 1, 1)
        self.descriptionTdt = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.descriptionTdt.setObjectName("descriptionTdt")
        self.gridLayout.addWidget(self.descriptionTdt, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.criticalityCmb = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.criticalityCmb.setObjectName("criticalityCmb")
        self.gridLayout.addWidget(self.criticalityCmb, 5, 1, 1, 1)
        self.usageCmb = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.usageCmb.setObjectName("usageCmb")
        self.gridLayout.addWidget(self.usageCmb, 6, 1, 1, 1)
        self.functionalityAdderBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.functionalityAdderBtn.setObjectName("functionalityAdderBtn")
        self.gridLayout.addWidget(self.functionalityAdderBtn, 3, 1, 1, 1)
        self.cancelBtn = QtWidgets.QPushButton(FunctionalityForm)
        self.cancelBtn.setGeometry(QtCore.QRect(1140, 700, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.addBtn = QtWidgets.QPushButton(FunctionalityForm)
        self.addBtn.setGeometry(QtCore.QRect(1140, 30, 75, 23))
        self.addBtn.setObjectName("addBtn")
        self.resetBtn = QtWidgets.QPushButton(FunctionalityForm)
        self.resetBtn.setGeometry(QtCore.QRect(1140, 60, 75, 23))
        self.resetBtn.setObjectName("resetBtn")

        self.retranslateUi(FunctionalityForm)
        QtCore.QMetaObject.connectSlotsByName(FunctionalityForm)
        FunctionalityForm.setTabOrder(self.idLdt, self.nameLdt)
        FunctionalityForm.setTabOrder(self.nameLdt, self.channelCmb)
        FunctionalityForm.setTabOrder(self.channelCmb, self.criticalityCmb)
        FunctionalityForm.setTabOrder(self.criticalityCmb, self.usageCmb)
        FunctionalityForm.setTabOrder(self.usageCmb, self.addBtn)
        FunctionalityForm.setTabOrder(self.addBtn, self.resetBtn)
        FunctionalityForm.setTabOrder(self.resetBtn, self.cancelBtn)
        FunctionalityForm.setTabOrder(self.cancelBtn, self.functionalityAdderBtn)
        FunctionalityForm.setTabOrder(self.functionalityAdderBtn, self.descriptionTdt)

    def retranslateUi(self, FunctionalityForm):
        _translate = QtCore.QCoreApplication.translate
        FunctionalityForm.setWindowTitle(_translate("FunctionalityForm", "Dialog"))
        self.label.setText(_translate("FunctionalityForm", "Channel"))
        self.label_2.setText(_translate("FunctionalityForm", "Name"))
        self.label_3.setText(_translate("FunctionalityForm", "Description"))
        self.ID.setText(_translate("FunctionalityForm", "ID"))
        self.label_4.setText(_translate("FunctionalityForm", "Criticality"))
        self.label_5.setText(_translate("FunctionalityForm", "Usage"))
        self.functionalityAdderBtn.setText(_translate("FunctionalityForm", "Add Application/Channel/Component/System"))
        self.cancelBtn.setText(_translate("FunctionalityForm", "Cancel"))
        self.addBtn.setText(_translate("FunctionalityForm", "Add"))
        self.resetBtn.setText(_translate("FunctionalityForm", "Reset"))

