# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1680, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addFeatureBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addFeatureBtn.setGeometry(QtCore.QRect(1280, 80, 75, 23))
        self.addFeatureBtn.setObjectName("addFeatureBtn")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(20, 20, 1221, 821))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.addThemeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addThemeBtn.setGeometry(QtCore.QRect(1280, 20, 75, 23))
        self.addThemeBtn.setObjectName("addThemeBtn")
        self.addEpicBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addEpicBtn.setGeometry(QtCore.QRect(1280, 50, 75, 23))
        self.addEpicBtn.setObjectName("addEpicBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1680, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Repository = QtWidgets.QAction(MainWindow)
        self.actionOpen_Repository.setObjectName("actionOpen_Repository")
        self.actionSave_Repository = QtWidgets.QAction(MainWindow)
        self.actionSave_Repository.setObjectName("actionSave_Repository")
        self.actionNew_Repository = QtWidgets.QAction(MainWindow)
        self.actionNew_Repository.setObjectName("actionNew_Repository")
        self.actionExport_feature = QtWidgets.QAction(MainWindow)
        self.actionExport_feature.setObjectName("actionExport_feature")
        self.actionImport_from_TestInsight = QtWidgets.QAction(MainWindow)
        self.actionImport_from_TestInsight.setObjectName("actionImport_from_TestInsight")
        self.actionClose_Repository = QtWidgets.QAction(MainWindow)
        self.actionClose_Repository.setObjectName("actionClose_Repository")
        self.actionImport_Excel = QtWidgets.QAction(MainWindow)
        self.actionImport_Excel.setObjectName("actionImport_Excel")
        self.actionRepository_settings = QtWidgets.QAction(MainWindow)
        self.actionRepository_settings.setObjectName("actionRepository_settings")
        self.actionConnect_to_Jira = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_Jira.setObjectName("actionConnect_to_Jira")
        self.menuTest.addAction(self.actionNew_Repository)
        self.menuTest.addAction(self.actionOpen_Repository)
        self.menuTest.addAction(self.actionSave_Repository)
        self.menuTest.addAction(self.actionClose_Repository)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionConnect_to_Jira)
        self.menuTest.addAction(self.actionRepository_settings)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionExit)
        self.menuExport.addAction(self.actionExport_feature)
        self.menuImport.addAction(self.actionImport_Excel)
        self.menuImport.addAction(self.actionImport_from_TestInsight)
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addFeatureBtn.setText(_translate("MainWindow", "Add Feature"))
        self.addThemeBtn.setText(_translate("MainWindow", "Add Theme"))
        self.addEpicBtn.setText(_translate("MainWindow", "Add Epic"))
        self.menuTest.setTitle(_translate("MainWindow", "Repository"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen_Repository.setText(_translate("MainWindow", "Open Repository"))
        self.actionOpen_Repository.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Repository.setText(_translate("MainWindow", "Save Repository"))
        self.actionSave_Repository.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionNew_Repository.setText(_translate("MainWindow", "New Repository"))
        self.actionNew_Repository.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionExport_feature.setText(_translate("MainWindow", "Export feature to gherkins"))
        self.actionImport_from_TestInsight.setText(_translate("MainWindow", "Import from TestInsight"))
        self.actionClose_Repository.setText(_translate("MainWindow", "Close Repository"))
        self.actionClose_Repository.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionImport_Excel.setText(_translate("MainWindow", "Import Excel"))
        self.actionRepository_settings.setText(_translate("MainWindow", "Repository settings"))
        self.actionConnect_to_Jira.setText(_translate("MainWindow", "Connect to Jira"))

