# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScenarioForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScenarioForm(object):
    def setupUi(self, ScenarioForm):
        ScenarioForm.setObjectName("ScenarioForm")
        ScenarioForm.resize(669, 986)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScenarioForm.sizePolicy().hasHeightForWidth())
        ScenarioForm.setSizePolicy(sizePolicy)
        ScenarioForm.setMinimumSize(QtCore.QSize(650, 290))
        ScenarioForm.setMaximumSize(QtCore.QSize(698, 1088))
        ScenarioForm.setSizeIncrement(QtCore.QSize(10, 10))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ScenarioForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ScenarioForm)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scenarioNameLdt = QtWidgets.QLineEdit(ScenarioForm)
        self.scenarioNameLdt.setObjectName("scenarioNameLdt")
        self.horizontalLayout.addWidget(self.scenarioNameLdt)
        self.AddScenarioBtn = QtWidgets.QPushButton(ScenarioForm)
        self.AddScenarioBtn.setObjectName("AddScenarioBtn")
        self.horizontalLayout.addWidget(self.AddScenarioBtn)
        self.CancelBtn = QtWidgets.QPushButton(ScenarioForm)
        self.CancelBtn.setObjectName("CancelBtn")
        self.horizontalLayout.addWidget(self.CancelBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ScenarioForm)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.GivenAddDataBtn = QtWidgets.QPushButton(ScenarioForm)
        self.GivenAddDataBtn.setObjectName("GivenAddDataBtn")
        self.horizontalLayout_2.addWidget(self.GivenAddDataBtn)
        self.GivenAddStepBtn = QtWidgets.QPushButton(ScenarioForm)
        self.GivenAddStepBtn.setObjectName("GivenAddStepBtn")
        self.horizontalLayout_2.addWidget(self.GivenAddStepBtn)
        self.GivenRemoveBtn = QtWidgets.QPushButton(ScenarioForm)
        self.GivenRemoveBtn.setObjectName("GivenRemoveBtn")
        self.horizontalLayout_2.addWidget(self.GivenRemoveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.GivenTab = QtWidgets.QTableWidget(ScenarioForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GivenTab.sizePolicy().hasHeightForWidth())
        self.GivenTab.setSizePolicy(sizePolicy)
        self.GivenTab.setMinimumSize(QtCore.QSize(649, 30))
        self.GivenTab.setMaximumSize(QtCore.QSize(649, 200))
        self.GivenTab.setSizeIncrement(QtCore.QSize(10, 10))
        self.GivenTab.setBaseSize(QtCore.QSize(649, 100))
        self.GivenTab.setObjectName("GivenTab")
        self.GivenTab.setColumnCount(0)
        self.GivenTab.setRowCount(0)
        self.verticalLayout.addWidget(self.GivenTab)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(ScenarioForm)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setBaseSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.WhenAddDataBtn = QtWidgets.QPushButton(ScenarioForm)
        self.WhenAddDataBtn.setObjectName("WhenAddDataBtn")
        self.horizontalLayout_3.addWidget(self.WhenAddDataBtn)
        self.WhenAddStepBtn = QtWidgets.QPushButton(ScenarioForm)
        self.WhenAddStepBtn.setObjectName("WhenAddStepBtn")
        self.horizontalLayout_3.addWidget(self.WhenAddStepBtn)
        self.WhenRemoveBtn = QtWidgets.QPushButton(ScenarioForm)
        self.WhenRemoveBtn.setObjectName("WhenRemoveBtn")
        self.horizontalLayout_3.addWidget(self.WhenRemoveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.WhenTab = QtWidgets.QTableWidget(ScenarioForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhenTab.sizePolicy().hasHeightForWidth())
        self.WhenTab.setSizePolicy(sizePolicy)
        self.WhenTab.setMinimumSize(QtCore.QSize(649, 30))
        self.WhenTab.setMaximumSize(QtCore.QSize(649, 200))
        self.WhenTab.setSizeIncrement(QtCore.QSize(10, 10))
        self.WhenTab.setBaseSize(QtCore.QSize(649, 100))
        self.WhenTab.setObjectName("WhenTab")
        self.WhenTab.setColumnCount(0)
        self.WhenTab.setRowCount(0)
        self.verticalLayout.addWidget(self.WhenTab)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(ScenarioForm)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ThenAddDataBtn = QtWidgets.QPushButton(ScenarioForm)
        self.ThenAddDataBtn.setObjectName("ThenAddDataBtn")
        self.horizontalLayout_4.addWidget(self.ThenAddDataBtn)
        self.ThenAddStepBtn = QtWidgets.QPushButton(ScenarioForm)
        self.ThenAddStepBtn.setObjectName("ThenAddStepBtn")
        self.horizontalLayout_4.addWidget(self.ThenAddStepBtn)
        self.ThenRemoveBtn = QtWidgets.QPushButton(ScenarioForm)
        self.ThenRemoveBtn.setObjectName("ThenRemoveBtn")
        self.horizontalLayout_4.addWidget(self.ThenRemoveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.ThenTab = QtWidgets.QTableWidget(ScenarioForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThenTab.sizePolicy().hasHeightForWidth())
        self.ThenTab.setSizePolicy(sizePolicy)
        self.ThenTab.setMinimumSize(QtCore.QSize(649, 30))
        self.ThenTab.setMaximumSize(QtCore.QSize(649, 200))
        self.ThenTab.setSizeIncrement(QtCore.QSize(10, 10))
        self.ThenTab.setBaseSize(QtCore.QSize(649, 100))
        self.ThenTab.setObjectName("ThenTab")
        self.ThenTab.setColumnCount(0)
        self.ThenTab.setRowCount(0)
        self.verticalLayout.addWidget(self.ThenTab)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(ScenarioForm)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.AddExampleBtn = QtWidgets.QPushButton(ScenarioForm)
        self.AddExampleBtn.setObjectName("AddExampleBtn")
        self.horizontalLayout_5.addWidget(self.AddExampleBtn)
        self.ExampleRemoveBtn = QtWidgets.QPushButton(ScenarioForm)
        self.ExampleRemoveBtn.setObjectName("ExampleRemoveBtn")
        self.horizontalLayout_5.addWidget(self.ExampleRemoveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.ExampleTab = QtWidgets.QTableWidget(ScenarioForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExampleTab.sizePolicy().hasHeightForWidth())
        self.ExampleTab.setSizePolicy(sizePolicy)
        self.ExampleTab.setMinimumSize(QtCore.QSize(649, 30))
        self.ExampleTab.setMaximumSize(QtCore.QSize(649, 200))
        self.ExampleTab.setSizeIncrement(QtCore.QSize(10, 10))
        self.ExampleTab.setBaseSize(QtCore.QSize(649, 100))
        self.ExampleTab.setObjectName("ExampleTab")
        self.ExampleTab.setColumnCount(0)
        self.ExampleTab.setRowCount(0)
        self.verticalLayout.addWidget(self.ExampleTab)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ScenarioForm)
        QtCore.QMetaObject.connectSlotsByName(ScenarioForm)

    def retranslateUi(self, ScenarioForm):
        _translate = QtCore.QCoreApplication.translate
        ScenarioForm.setWindowTitle(_translate("ScenarioForm", "Dialog"))
        self.label.setText(_translate("ScenarioForm", "Scenario"))
        self.AddScenarioBtn.setText(_translate("ScenarioForm", "Add"))
        self.CancelBtn.setText(_translate("ScenarioForm", "Cancel"))
        self.label_2.setText(_translate("ScenarioForm", "Given"))
        self.GivenAddDataBtn.setText(_translate("ScenarioForm", "Add data array"))
        self.GivenAddStepBtn.setText(_translate("ScenarioForm", "Add step"))
        self.GivenRemoveBtn.setText(_translate("ScenarioForm", "Remove Last"))
        self.label_3.setText(_translate("ScenarioForm", "When"))
        self.WhenAddDataBtn.setText(_translate("ScenarioForm", "Add data array"))
        self.WhenAddStepBtn.setText(_translate("ScenarioForm", "Add step"))
        self.WhenRemoveBtn.setText(_translate("ScenarioForm", "Remove Last"))
        self.label_4.setText(_translate("ScenarioForm", "Then"))
        self.ThenAddDataBtn.setText(_translate("ScenarioForm", "Add data array"))
        self.ThenAddStepBtn.setText(_translate("ScenarioForm", "Add step"))
        self.ThenRemoveBtn.setText(_translate("ScenarioForm", "Remove Last"))
        self.label_5.setText(_translate("ScenarioForm", "Examples"))
        self.AddExampleBtn.setText(_translate("ScenarioForm", "Add example"))
        self.ExampleRemoveBtn.setText(_translate("ScenarioForm", "Remove Last"))

