# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UseCaseForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UseCaseForm(object):
    def setupUi(self, UseCaseForm):
        UseCaseForm.setObjectName("UseCaseForm")
        UseCaseForm.resize(1355, 840)
        self.gridLayoutWidget = QtWidgets.QWidget(UseCaseForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 1108, 790))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.useCaseID = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.useCaseID.setMinimumSize(QtCore.QSize(450, 20))
        self.useCaseID.setObjectName("useCaseID")
        self.gridLayout.addWidget(self.useCaseID, 0, 1, 1, 1)
        self.useCaseName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.useCaseName.setObjectName("useCaseName")
        self.gridLayout.addWidget(self.useCaseName, 0, 3, 1, 1)
        self.shortDesc = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.shortDesc.setMinimumSize(QtCore.QSize(450, 250))
        self.shortDesc.setObjectName("shortDesc")
        self.gridLayout.addWidget(self.shortDesc, 1, 1, 1, 1)
        self.preRequisite = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.preRequisite.setMinimumSize(QtCore.QSize(450, 250))
        self.preRequisite.setObjectName("preRequisite")
        self.gridLayout.addWidget(self.preRequisite, 2, 1, 1, 1)
        self.steps = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.steps.setMinimumSize(QtCore.QSize(450, 250))
        self.steps.setObjectName("steps")
        self.gridLayout.addWidget(self.steps, 3, 1, 1, 1)
        self.postCondition = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.postCondition.setMinimumSize(QtCore.QSize(450, 250))
        self.postCondition.setObjectName("postCondition")
        self.gridLayout.addWidget(self.postCondition, 2, 3, 1, 1)
        self.exceptionalBehaviour = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.exceptionalBehaviour.setMinimumSize(QtCore.QSize(450, 250))
        self.exceptionalBehaviour.setObjectName("exceptionalBehaviour")
        self.gridLayout.addWidget(self.exceptionalBehaviour, 3, 3, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.requireUseCaseCmb = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.requireUseCaseCmb.setObjectName("requireUseCaseCmb")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.requireUseCaseCmb)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.testTypeCmb = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.testTypeCmb.setObjectName("testTypeCmb")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.testTypeCmb)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.criticalPathCkb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.criticalPathCkb.setObjectName("criticalPathCkb")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.criticalPathCkb)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.linkFunctionalityCmb = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.linkFunctionalityCmb.setObjectName("linkFunctionalityCmb")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.linkFunctionalityCmb)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.linkAutomatonCmb = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.linkAutomatonCmb.setObjectName("linkAutomatonCmb")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.linkAutomatonCmb)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.automatedCkb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.automatedCkb.setObjectName("automatedCkb")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.automatedCkb)
        self.automatableCkb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.automatableCkb.setObjectName("automatableCkb")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.automatableCkb)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.averageTime = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.averageTime.setObjectName("averageTime")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.averageTime)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.releaseCmb = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.releaseCmb.setEditable(False)
        self.releaseCmb.setObjectName("releaseCmb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.releaseCmb)
        self.releaseAdderBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.releaseAdderBtn.setObjectName("releaseAdderBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.releaseAdderBtn)
        self.gridLayout.addLayout(self.formLayout, 1, 3, 1, 1)
        self.addBtn = QtWidgets.QPushButton(UseCaseForm)
        self.addBtn.setGeometry(QtCore.QRect(1140, 30, 75, 23))
        self.addBtn.setObjectName("addBtn")
        self.resetBtn = QtWidgets.QPushButton(UseCaseForm)
        self.resetBtn.setGeometry(QtCore.QRect(1140, 60, 75, 23))
        self.resetBtn.setObjectName("resetBtn")
        self.cancelBtn = QtWidgets.QPushButton(UseCaseForm)
        self.cancelBtn.setGeometry(QtCore.QRect(1140, 700, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(UseCaseForm)
        QtCore.QMetaObject.connectSlotsByName(UseCaseForm)

    def retranslateUi(self, UseCaseForm):
        _translate = QtCore.QCoreApplication.translate
        UseCaseForm.setWindowTitle(_translate("UseCaseForm", "Dialog"))
        self.label_4.setText(_translate("UseCaseForm", "Post Condition"))
        self.label.setText(_translate("UseCaseForm", "Use case ID"))
        self.label_2.setText(_translate("UseCaseForm", "Name"))
        self.label_3.setText(_translate("UseCaseForm", "Pre requisite"))
        self.label_5.setText(_translate("UseCaseForm", "Steps"))
        self.label_6.setText(_translate("UseCaseForm", "Exceptional Behaviour"))
        self.label_7.setText(_translate("UseCaseForm", "Short Description"))
        self.label_8.setText(_translate("UseCaseForm", "Require Use case"))
        self.label_9.setText(_translate("UseCaseForm", "Test Type"))
        self.label_10.setText(_translate("UseCaseForm", "Critical Path?"))
        self.criticalPathCkb.setText(_translate("UseCaseForm", "Yes"))
        self.label_11.setText(_translate("UseCaseForm", "Linked functionality"))
        self.label_12.setText(_translate("UseCaseForm", "Linked automaton"))
        self.label_13.setText(_translate("UseCaseForm", "Automatable?"))
        self.label_14.setText(_translate("UseCaseForm", "Automated?"))
        self.automatedCkb.setText(_translate("UseCaseForm", "Yes"))
        self.automatableCkb.setText(_translate("UseCaseForm", "Yes"))
        self.label_15.setText(_translate("UseCaseForm", "Average Run Time"))
        self.label_16.setText(_translate("UseCaseForm", "Release"))
        self.releaseAdderBtn.setText(_translate("UseCaseForm", "Add release"))
        self.addBtn.setText(_translate("UseCaseForm", "Add"))
        self.resetBtn.setText(_translate("UseCaseForm", "Reset"))
        self.cancelBtn.setText(_translate("UseCaseForm", "Cancel"))

